[package]
name = "linklake-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
getrandom.workspace = true
argon2.workspace = true
arc-swap.workspace = true
axum.workspace = true
axum-server.workspace = true
base64.workspace = true
bytes.workspace = true
chacha20poly1305.workspace = true
ed25519-dalek.workspace = true
fs2.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
hmac.workspace = true
instant-acme.workspace = true
linklake-core = { path = "../linklake-core", version = "=0.8.0-rc.1" }
linklake-update = { path = "../linklake-update", version = "=0.8.0-rc.1" }
quinn.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sha1.workspace = true
socket2.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tower-http.workspace = true
uuid.workspace = true
x509-parser.workspace = true
zeroize.workspace = true
rustls-pki-types.workspace = true
rustls.workspace = true
rustls-native-certs.workspace = true
rusqlite.workspace = true
semver.workspace = true
tracing-appender.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tar.workspace = true

[target.'cfg(windows)'.dependencies]
windows-service.workspace = true
windows-sys.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
rcgen = { version = "0.14.8", default-features = false, features = ["pem", "ring"] }
