[package]
name = "linklake-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
clap.workspace = true
ed25519-dalek.workspace = true
flate2.workspace = true
getrandom.workspace = true
iroh.workspace = true
linklake-core = { path = "../linklake-core", version = "=1.0.0-rc.1" }
linklake-update = { path = "../linklake-update", version = "=1.0.0-rc.1" }
quinn.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snow.workspace = true
tar.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
toml.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
rustls-pki-types.workspace = true
zip.workspace = true

[target.'cfg(windows)'.dependencies]
windows-service.workspace = true
rustls.workspace = true
